name: Build

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['**']

jobs:
    build:
        defaults:
          run:
            working-directory: UI
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Setup Node Environment
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Build Site
      run: npm run build --if-present
    - name: Deploy
      uses: burnett01/rsync-deployments@7.0.0
      with:
        switches: -avzr --delete
        path: build/
        remote_path: ${{ secrets.DEPLOY_PATH }}
        remote_host: ${{ secrets.DEPLOY_HOST }}
        remote_user: ${{ secrets.DEPLOY_USER }}
        remote_key: ${{ secrets.DEPLOY_KEY }}