name: Build

on:
  push:
    branches: ['main']

jobs:
  build:
    defaults:
      run:
        working-directory: UI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 20.x
    steps:
      - uses: actions/checkout@v3
      - name: 'Use Node.js ${{ matrix.node-version }}'
        uses: actions/setup-node@v3
        with:
          node-version: '${{ matrix.node-version }}'
          cache: npm
          cache-dependency-path: UI
      - run: npm ci
      - run: npm run build
      - name: Deploy
        uses: burnett01/rsync-deployments@7.0.0
        with:
                switches: -avzr --delete
                path: UI/build/
                remote_path: ${{ secrets.DEPLOY_PATH }}
                remote_host: ${{ secrets.DEPLOY_HOST }}
                remote_user: ${{ secrets.DEPLOY_USER }}
                remote_key: ${{ secrets.DEPLOY_KEY }}